version: '3'
services:
  dev:
    image: json_schema_extra:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ERL_AFLAGS: ${ERL_AFLAGS}
    volumes:
      - ./tmp/erlang-history:/root/.cache/erlang-history
      - ./lib:/usr/src/app/lib
      - ./mix.exs:/usr/src/app/mix.exs
      - ./mix.lock:/usr/src/app/mix.lock
      - ./test:/usr/src/app/test
      - elixir_build:/usr/src/app/_build
      - elixir_deps:/usr/src/app/deps

volumes:
  elixir_build:
  elixir_deps:
